<a href="https://colab.research.google.com/github/RohitGottapu/IIT-KGP-Resources/blob/main/Movie_Recommender_system_memory_based.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot

In [4]:
from google.colab import drive
# creates file in path in colab, files in drive are accesible to from colab
drive.mount('/content/movie_recommender')


Mounted at /content/movie_recommender


In [5]:
my_path = "/content/movie_recommender/My Drive/"

ratings=pd.read_csv(my_path + 'ratings.csv')

In [6]:
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [7]:
ratings.tail()

userId  movieId  rating   timestamp
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

In [8]:
ratings.shape

(100836, 4)

In [9]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype  
---  ------     --------------   -----  
 0   userId     100836 non-null  int64  
 1   movieId    100836 non-null  int64  
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64  
dtypes: float64(1), int64(3)
memory usage: 3.1 MB


In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test = train_test_split(ratings, test_size = 0.3, random_state=3)
print(X_train.head())
print(X_test.head())

        userId  movieId  rating   timestamp
61269      401   167036     3.0  1510450729
87015      561    88140     3.5  1491091312
100620     610   102445     3.0  1493845494
30384      212    58559     3.5  1490115412
18466      117      590     4.0   844162743
       userId  movieId  rating   timestamp
34979     234     1275     4.0  1004408188
47527     307    30822     2.5  1186172822
91599     594     1974     3.5  1108951254
18366     117       44     2.0   844163037
31050     217     1016     2.0   955944568


In [28]:
user_data = X_train.pivot(index= 'userId', columns = 'movieId', values = 'rating').fillna(0)
print(user_data.head())
print(user_data.shape)

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           0.0     0.0     4.0     0.0     0.0     4.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           4.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  190209  190215  191005  193565  193567  193573  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0

In [19]:
dummy_test = X_test.copy()
dummy_train = X_train.copy()

dummy_test['rating']= dummy_test['rating'].apply(lambda x: 1 if x>0 else 0)
dummy_train['rating']= dummy_train['rating'].apply(lambda x: 0 if x>0 else 1)



In [20]:
dummy_train = dummy_train.pivot(index='userId', columns='movieId', values='rating').fillna(1)
dummy_test = dummy_test.pivot(index='userId', columns='movieId', values='rating').fillna(0)

In [21]:
dummy_train.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           1.0     1.0     0.0     1.0     1.0     0.0     1.0     1.0   
2           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   
5           0.0     1.0     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  9       10      ...  190209  190215  191005  193565  193567  193573  \
userId                   ...                                                   
1           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
2           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
3           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
4           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   
5           1.0     1.0  ...     1.0     1.0     1.0     1.0     1.0     1.0   

movieId  193579  193581  193583  193587  
userId                                   
1           1.0     1.0     1.0     1.0  
2           1.0     1.0     1.0     1.0  
3           1.0     1.0     1.0     1.0  
4           1.0     1.0     1.0     1.0  
5           1.0     1.0     1.0     1.0  

[5 rows x 8545 columns]

In [22]:
dummy_test.head()

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           1.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  9       10      ...  188751  188833  189333  189547  190213  190219  \
userId                   ...                                                   
1           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
2           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
3           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
4           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   
5           0.0     0.0  ...     0.0     0.0     0.0     0.0     0.0     0.0   

movieId  190221  193571  193585  193609  
userId                                   
1           0.0     0.0     0.0     0.0  
2           0.0     0.0     0.0     0.0  
3           0.0     0.0     0.0     0.0  
4           0.0     0.0     0.0     0.0  
5           0.0     0.0     0.0     0.0  

[5 rows x 6127 columns]

In [27]:
# # check what happens using Eucldian similarity
# using cosine distance
# from sklearn.metrics.pairwise import pairwise_distances

# # User Similarity Matrix using Cosine similarity as a similarity measure between Users
# user_similarity = 1 - pairwise_distances(user_data, metric = 'cosine')
# user_similarity[np.isnan(user_similarity)] = 0
# print(user_similarity)
# print(user_similarity.shape)

from sklearn.metrics.pairwise import cosine_similarity

# User Similarity Matrix using Cosine similarity as a similarity measure between Users
user_similarity = cosine_similarity(user_data)
user_similarity[np.isnan(user_similarity)] = 0
print(user_similarity)
print(user_similarity.shape)

[[1.         0.02035686 0.02950532 ... 0.21365248 0.03962784 0.07215582]
 [0.02035686 1.         0.         ... 0.04798005 0.         0.04525289]
 [0.02950532 0.         1.         ... 0.02530522 0.         0.03201404]
 ...
 [0.21365248 0.04798005 0.02530522 ... 1.         0.07049114 0.23145897]
 [0.03962784 0.         0.         ... 0.07049114 1.         0.03789709]
 [0.07215582 0.04525289 0.03201404 ... 0.23145897 0.03789709 1.        ]]
(610, 610)


In [30]:
user_prediction_ratings = np.dot(user_similarity, user_data)
print(user_prediction_ratings.shape)

(610, 8545)


In [31]:
user_final_predictions = np.multiply(user_prediction_ratings, dummy_train)
print(user_final_predictions.head)

<bound method NDFrame.head of movieId      1          2          3         4          5          6       \
userId                                                                      
1         65.946329  29.794757   0.000000  1.252945   9.644508   0.000000   
2         17.172949   8.150709   1.626739  0.000000   1.758547   6.967792   
3          4.789754   2.229291   1.317414  0.049535   0.638250   2.975120   
4         53.055975  20.944315  10.491385  1.142003   7.316375  26.512152   
5          0.000000  32.910977  11.452947  2.668232  11.890715  32.589141   
...             ...        ...        ...       ...        ...        ...   
606        0.000000  31.457151  12.586086  1.451763   9.539160  37.215228   
607        0.000000  34.536454  15.573615  1.657009  11.701117  43.351167   
608      104.498533   0.000000   0.000000  1.470634  14.560531  56.182885   
609       50.583511  29.537150   9.182264  1.965741   9.555787  28.518464   
610        0.000000  34.618721  10.046431  0.8

In [32]:
user_final_predictions.iloc[42].sort_values(ascending= False)[0:5]

movieId
480    87.053488
593    84.624236
592    76.890773
380    76.636760
1      64.991126
Name: 43, dtype: float64